# Generated by Django 5.1.5 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('SAMSUNG', 'Samsung'), ('MOTOROLA', 'Motorola'), ('XIAOMI', 'Xiaomi'), ('IPHONE', 'iPhone'), ('LG', 'LG'), ('ASUS', 'Asus'), ('MULTILASER', 'Multilaser')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('preco_desbloqueio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
