# Generated by Django 5.1.5 on 2025-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='marca',
            field=models.CharField(choices=[('SAMSUNG', 'Samsung'), ('MOTOROLA', 'Motorola'), ('XIAOMI', 'Xiaomi'), ('IPHONE', 'iPhone'), ('LG', 'LG'), ('ASUS', 'Asus'), ('MULTILASER', 'Multilaser')], max_length=20),
        ),
    ]
